# Generated by Django 5.2.8 on 2026-01-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='config',
            field=models.JSONField(blank=True, db_column='Config', default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='is_visible',
            field=models.BooleanField(db_column='IsVisible', default=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position',
            field=models.IntegerField(db_column='Position', default=0),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='title',
            field=models.CharField(db_column='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='user',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('stats', 'Statistics'), ('chart', 'Chart'), ('list', 'List'), ('calendar', 'Calendar')], db_column='WidgetType', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_column='IsRead', default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, db_column='Link', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(db_column='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_column='NotificationType', default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, db_column='ReadAt', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(db_column='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
